import { MOUSE, TOUCH } from "three";

export const SCENE_CAMERA_MOUSE_BUTTONS = {
  LEFT: MOUSE.PAN,
  MIDDLE: MOUSE.DOLLY,
  RIGHT: MOUSE.PAN,
} as const;

export const SCENE_CAMERA_TOUCHES = {
  ONE: TOUCH.PAN,
  TWO: TOUCH.DOLLY_PAN,
} as const;

export const ORTHOGRAPHIC_CAMERA_DAMPING_FACTOR = 0.08;
export const ORTHOGRAPHIC_CAMERA_ZOOM_SPEED = 0.45;
export const ORTHOGRAPHIC_CAMERA_PAN_SPEED = 1;
export const ORTHOGRAPHIC_CAMERA_TOOLBAR_ZOOM_SCALE = 1.16;
