import type { CabinetCatalogItem } from "./types";
import {
  BASE_BLIND_WIDTH_OPTIONS,
  BASE_FARM_SINK_WIDTH_OPTIONS,
  BASE_MICROWAVE_DEPTH_OPTIONS,
  BASE_MICROWAVE_HEIGHT_OPTIONS,
  BASE_MICROWAVE_WIDTH_OPTIONS,
  BASE_NARROW_WIDTH_OPTIONS,
  BASE_ONE_DOOR_PANTRY_WIDTH_OPTIONS,
  BASE_OVEN_DEPTH_OPTIONS,
  BASE_OVEN_HEIGHT_OPTIONS,
  BASE_OVEN_WIDTH_OPTIONS,
  BASE_PANTRY_DEPTH_OPTIONS,
  BASE_PANTRY_HEIGHT_OPTIONS,
  BASE_SINK_WIDTH_OPTIONS,
  BASE_SPICE_RACK_WIDTH_OPTIONS,
  BASE_STANDARD_DEPTH_OPTIONS,
  BASE_STANDARD_HEIGHT_OPTIONS,
  BASE_THREE_DRAWER_WIDTH_OPTIONS,
  BASE_TRASH_CAN_WIDTH_OPTIONS,
  BASE_TWO_DOOR_PANTRY_WIDTH_OPTIONS,
  BASE_TWO_DRAWER_WIDTH_OPTIONS,
  BASE_WIDE_WIDTH_OPTIONS,
  WALL_ONE_DOOR_WIDTH_OPTIONS,
  WALL_PANTRY_DEPTH_OPTIONS,
  WALL_PANTRY_HEIGHT_OPTIONS,
  WALL_STANDARD_DEPTH_OPTIONS,
  WALL_STANDARD_HEIGHT_OPTIONS,
  WALL_TWO_DOOR_WIDTH_OPTIONS,
} from "./catalogOptions";

export const CABINET_CATALOG: CabinetCatalogItem[] = [
  {
    id: "base-corner-cabinet",
    category: "base",
    title: "L-Shaped Corner Base Cabinet",
    subtitle: '36" W x 36" H x 36" D',
    widthInches: 36,
    heightInches: 36,
    depthInches: 36,
    image: "base-corner",
  },
  {
    id: "product-dishwasher",
    category: "base",
    title: "Dishwashing Machine",
    subtitle: '24" W x 34" H x 24" D',
    widthInches: 24,
    heightInches: 34,
    depthInches: 24,
    image: "base-dishwasher",
    isProduct: true,
    productCategory: "base",
  },
  {
    id: "product-refrigerator",
    category: "base",
    title: "Refrigerator",
    subtitle: '36" W x 84" H x 30" D',
    widthInches: 36,
    heightInches: 84,
    depthInches: 30,
    image: "base-refrigerator",
    isProduct: true,
    productCategory: "base",
  },
  {
    id: "product-range",
    category: "base",
    title: "Range",
    subtitle: '30" W x 36" H x 24" D',
    widthInches: 30,
    heightInches: 36,
    depthInches: 24,
    image: "base-range",
    isProduct: true,
    productCategory: "base",
  },
  {
    id: "base-two-door-cabinet",
    category: "base",
    title: "2 Door Base Cabinet",
    subtitle: '24" W x 34.5" H x 24" D',
    widthInches: 24,
    heightInches: 34.5,
    depthInches: 24,
    image: "base",
    standardWidthOptions: BASE_WIDE_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-one-door-cabinet",
    category: "base",
    title: "1 Door Base Cabinet",
    subtitle: '9" W x 34.5" H x 24" D',
    widthInches: 9,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-one-door",
    standardWidthOptions: BASE_NARROW_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-drawer-cabinet",
    category: "base",
    title: "3 Drawers Base Cabinet",
    subtitle: '9" W x 34.5" H x 24" D',
    widthInches: 9,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-drawer",
    standardWidthOptions: BASE_THREE_DRAWER_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-sink-cabinet",
    category: "base",
    title: "Sink Base Cabinet",
    subtitle: '24" W x 34.5" H x 24" D',
    widthInches: 24,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-sink-cabinet",
    standardWidthOptions: BASE_SINK_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-farm-sink-cabinet",
    category: "base",
    title: "Sink Farm Base Cabinet",
    subtitle: '30" W x 34.5" H x 24" D',
    widthInches: 30,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-farm-sink-cabinet",
    standardWidthOptions: BASE_FARM_SINK_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-blind-left-cabinet",
    category: "base",
    title: "1 Door Blind (Left) Base Cabinet",
    subtitle: '36" W x 34.5" H x 24" D',
    widthInches: 36,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-blind-left",
    standardWidthOptions: BASE_BLIND_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-blind-right-cabinet",
    category: "base",
    title: "1 Door Blind (Right) Base Cabinet",
    subtitle: '36" W x 34.5" H x 24" D',
    widthInches: 36,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-blind-right",
    standardWidthOptions: BASE_BLIND_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-two-door-one-drawer-cabinet",
    category: "base",
    title: "1 Top Drawer, 2 Doors Base Cabinet",
    subtitle: '24" W x 34.5" H x 24" D',
    widthInches: 24,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-two-door-one-drawer",
    standardWidthOptions: BASE_WIDE_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-one-door-one-drawer-cabinet",
    category: "base",
    title: "1 Top Drawer, 1 Door Base Cabinet",
    subtitle: '9" W x 34.5" H x 24" D',
    widthInches: 9,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-one-door-one-drawer",
    standardWidthOptions: BASE_NARROW_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-two-door-two-drawer-cabinet",
    category: "base",
    title: "2 Top Drawers, 2 Doors Base Cabinet",
    subtitle: '24" W x 34.5" H x 24" D',
    widthInches: 24,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-two-door-two-drawer",
    standardWidthOptions: BASE_WIDE_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-two-drawer-cabinet",
    category: "base",
    title: "2 Drawer Base Cabinet",
    subtitle: '9" W x 34.5" H x 24" D',
    widthInches: 9,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-two-drawer",
    standardWidthOptions: BASE_TWO_DRAWER_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-spice-rack-cabinet",
    category: "base",
    title: "Spice Rack Base Cabinet",
    subtitle: '6" W x 34.5" H x 24" D',
    widthInches: 6,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-spice-rack",
    standardWidthOptions: BASE_SPICE_RACK_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-trash-can-cabinet",
    category: "base",
    title: "Trash Can Base Cabinet",
    subtitle: '12" W x 34.5" H x 24" D',
    widthInches: 12,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-trash-can",
    standardWidthOptions: BASE_TRASH_CAN_WIDTH_OPTIONS,
    standardHeightOptions: BASE_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "base-oven-bottom-drawer-cabinet",
    category: "base",
    title: "Oven with 1 Bottom Drawer Base Cabinet",
    subtitle: '30" W x 69" H x 26" D',
    widthInches: 30,
    heightInches: 69,
    depthInches: 26,
    image: "base-oven-bottom-drawer",
    standardWidthOptions: BASE_OVEN_WIDTH_OPTIONS,
    standardHeightOptions: BASE_OVEN_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_OVEN_DEPTH_OPTIONS,
  },
  {
    id: "base-microwave-bottom-drawer-cabinet",
    category: "base",
    title: "Microwave with 1 Bottom Drawer Base Cabinet",
    subtitle: '24" W x 34.5" H x 24" D',
    widthInches: 24,
    heightInches: 34.5,
    depthInches: 24,
    image: "base-microwave-bottom-drawer",
    standardWidthOptions: BASE_MICROWAVE_WIDTH_OPTIONS,
    standardHeightOptions: BASE_MICROWAVE_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_MICROWAVE_DEPTH_OPTIONS,
  },
  {
    id: "base-pantry-one-door-cabinet",
    category: "base",
    title: "1 Door Pantry Cabinet (Base)",
    subtitle: '9" W x 54" H x 24" D',
    widthInches: 9,
    heightInches: 54,
    depthInches: 24,
    image: "pantry-one-door",
    standardWidthOptions: BASE_ONE_DOOR_PANTRY_WIDTH_OPTIONS,
    standardHeightOptions: BASE_PANTRY_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_PANTRY_DEPTH_OPTIONS,
  },
  {
    id: "base-pantry-two-door-cabinet",
    category: "base",
    title: "2 Door Pantry Cabinet (Base)",
    subtitle: '24" W x 54" H x 24" D',
    widthInches: 24,
    heightInches: 54,
    depthInches: 24,
    image: "pantry-two-door",
    standardWidthOptions: BASE_TWO_DOOR_PANTRY_WIDTH_OPTIONS,
    standardHeightOptions: BASE_PANTRY_HEIGHT_OPTIONS,
    standardDepthOptions: BASE_PANTRY_DEPTH_OPTIONS,
  },
  {
    id: "wall-two-door-cabinet",
    category: "wall",
    title: "2 Door Wall Cabinet",
    subtitle: '24" W x 12" H x 12" D',
    widthInches: 24,
    heightInches: 12,
    depthInches: 12,
    image: "wall-two-doors",
    standardWidthOptions: WALL_TWO_DOOR_WIDTH_OPTIONS,
    standardHeightOptions: WALL_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: WALL_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "wall-one-door-cabinet",
    category: "wall",
    title: "1 Door Wall Cabinet",
    subtitle: '9" W x 12" H x 12" D',
    widthInches: 9,
    heightInches: 12,
    depthInches: 12,
    image: "wall-one-door",
    standardWidthOptions: WALL_ONE_DOOR_WIDTH_OPTIONS,
    standardHeightOptions: WALL_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: WALL_STANDARD_DEPTH_OPTIONS,
  },
  {
    id: "wall-blind-left-cabinet",
    category: "wall",
    title: "1 Door Blind (Left) Wall Cabinet",
    subtitle: '36" W x 12" H x 12" D',
    widthInches: 36,
    heightInches: 12,
    depthInches: 12,
    image: "wall-blind-left",
    standardWidthOptions: BASE_BLIND_WIDTH_OPTIONS,
    standardHeightOptions: WALL_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: WALL_STANDARD_DEPTH_OPTIONS,
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "wall-blind-right-cabinet",
    category: "wall",
    title: "1 Door Blind (Right) Wall Cabinet",
    subtitle: '36" W x 12" H x 12" D',
    widthInches: 36,
    heightInches: 12,
    depthInches: 12,
    image: "wall-blind-right",
    standardWidthOptions: BASE_BLIND_WIDTH_OPTIONS,
    standardHeightOptions: WALL_STANDARD_HEIGHT_OPTIONS,
    standardDepthOptions: WALL_STANDARD_DEPTH_OPTIONS,
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "wall-pantry-one-door-cabinet",
    category: "wall",
    title: "1 Door Pantry Cabinet (Wall)",
    subtitle: '9" W x 12" H x 24" D',
    widthInches: 9,
    heightInches: 12,
    depthInches: 24,
    image: "pantry-one-door",
    standardWidthOptions: WALL_ONE_DOOR_WIDTH_OPTIONS,
    standardHeightOptions: WALL_PANTRY_HEIGHT_OPTIONS,
    standardDepthOptions: WALL_PANTRY_DEPTH_OPTIONS,
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "wall-pantry-two-door-cabinet",
    category: "wall",
    title: "2 Doors Pantry Cabinet (Wall)",
    subtitle: '24" W x 12" H x 24" D',
    widthInches: 24,
    heightInches: 12,
    depthInches: 24,
    image: "pantry-two-door",
    standardWidthOptions: WALL_TWO_DOOR_WIDTH_OPTIONS,
    standardHeightOptions: WALL_PANTRY_HEIGHT_OPTIONS,
    standardDepthOptions: WALL_PANTRY_DEPTH_OPTIONS,
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "product-wall-hood",
    category: "wall",
    title: "Hood",
    subtitle: '30" W x 24" H x 12" D',
    widthInches: 30,
    heightInches: 24,
    depthInches: 12,
    image: "wall-hood",
    isProduct: true,
    productCategory: "wall",
    defaultDistanceFromFloorInches: 60,
  },
  {
    id: "product-wall-microwave",
    category: "wall",
    title: "Microwave",
    subtitle: '30" W x 18" H x 15" D',
    widthInches: 30,
    heightInches: 18,
    depthInches: 15,
    image: "wall-microwave",
    isProduct: true,
    productCategory: "wall",
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "product-wall-oven",
    category: "wall",
    title: "Single Oven",
    subtitle: '30" W x 30" H x 24" D',
    widthInches: 30,
    heightInches: 30,
    depthInches: 24,
    image: "wall-oven",
    isProduct: true,
    productCategory: "wall",
    defaultDistanceFromFloorInches: 42,
  },
  {
    id: "product-wall-double-oven",
    category: "wall",
    title: "Double Oven",
    subtitle: '30" W x 54" H x 24" D',
    widthInches: 30,
    heightInches: 54,
    depthInches: 24,
    image: "wall-double-oven",
    isProduct: true,
    productCategory: "wall",
    defaultDistanceFromFloorInches: 18,
  },
  {
    id: "accessory-base-filler",
    category: "base",
    title: "Base Filler",
    subtitle: '4" W x 34.5" H x 24" D',
    widthInches: 4,
    heightInches: 34.5,
    depthInches: 24,
    image: "accessory-base-filler",
    isAccessory: true,
    accessoryKind: "base-filler",
  },
  {
    id: "accessory-wall-filler",
    category: "wall",
    title: "Wall Filler (Vertical)",
    subtitle: '4" W x 30" H x 12" D',
    widthInches: 4,
    heightInches: 30,
    depthInches: 12,
    image: "accessory-wall-filler",
    isAccessory: true,
    accessoryKind: "wall-filler",
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "accessory-wall-filler-horizontal",
    category: "wall",
    title: "Wall Filler (Horizontal)",
    subtitle: '36" W x 3" H x 24" D',
    widthInches: 36,
    heightInches: 3,
    depthInches: 24,
    image: "accessory-wall-filler-horizontal",
    isAccessory: true,
    accessoryKind: "wall-filler",
    defaultDistanceFromFloorInches: 54,
  },
  {
    id: "accessory-base-end-panel",
    category: "base",
    title: "Base End Panel",
    subtitle: '4" W x 34.5" H x 36" D',
    widthInches: 4,
    heightInches: 34.5,
    depthInches: 36,
    image: "accessory-base-end-panel",
    isAccessory: true,
    accessoryKind: "base-end-panel",
  },
  {
    id: "accessory-wall-end-panel",
    category: "wall",
    title: "Wall End Panel",
    subtitle: '4" W x 30" H x 12" D',
    widthInches: 4,
    heightInches: 30,
    depthInches: 12,
    image: "accessory-wall-end-panel",
    isAccessory: true,
    accessoryKind: "wall-end-panel",
    defaultDistanceFromFloorInches: 54,
  },
];
