

export const WALL_ATTACH_THRESHOLD = 22;

export const WALL_STROKE_WIDTH = 16;

export const WALL_THICKNESS = WALL_STROKE_WIDTH;

export const PENIN_WALL_THICKNESS = WALL_THICKNESS * 2;

export const PENIN_WALL_ELEVATION_HEIGHT_INCHES = 36;

export const PENIN_WALL_ELEVATION_FACE_WIDTH_INCHES = 24;

export const THIN_WALL_STROKE_WIDTH = 2;
