import type { Point3DInches } from "@/core/geometry/pointTypes";
import type { CabinetPlacementRequirement, WallFaceSide, WallSettings } from "@/engine/walls/placedWallSegmentTypes";
import type { AssemblyOptionValue } from "@/engine/assemblies/assemblyConfiguration";
import type { DesignReservationZonePurpose } from "@/engine/design-zones/designReservationZoneTypes";
import type { SceneEntity, SceneEntityRef } from "@/engine/scene-entities/sceneEntityTypes";
import type { SceneEntityAlignmentGuide } from "@/engine/scene-entities/spatial-guides/spatialGuideTypes";
import type { SceneEntityElevationFrame, SceneDragState } from "./sceneDragTypes";
import type { SceneEntityMovementFrame } from "@/engine/scene-entities/sceneEntityMovementFrame";
import type { WallElevationTarget } from "@/engine/walls/wallSegmentElevationTypes";
import type { SceneEditingTool } from "./sceneEditingToolTypes";
import type { SceneCameraCommand, SceneCameraCommandTool } from "@/engine/scene/sceneCameraCommandTypes";
import type { SceneCameraStates, ElevationCameraState, OrthographicCameraState, PerspectiveCameraState } from "@/engine/scene/sceneCameraStateTypes";
import type { SceneViewMode } from "@/engine/scene/sceneViewModeTypes";
import type { DesignScene } from "./designSceneTypes";
import type { DesignSceneHistoryState } from "./sceneHistoryTypes";

export type AssemblyDimensionId = "widthInches" | "depthInches" | "heightInches";

export type SceneEntityWallMeasurementLabelScreenItem = Readonly<{
  id: string;
  xPixels: number;
  yPixels: number;
  lengthInches: number;
  labelRotationDegrees: number;
}>;

export type DesignSceneStore = Readonly<{
  designScene: DesignScene;
  wallSettings: WallSettings;
  activeSceneViewMode: SceneViewMode;
  activeWallElevationTarget: WallElevationTarget | null;
  activeToolbarTool: SceneEditingTool | null;
  cameraCommand: SceneCameraCommand | null;
  sceneCameraStates: SceneCameraStates;
  activeDrag: SceneDragState | null;
  activeSceneEntityAlignmentGuides: readonly SceneEntityAlignmentGuide[];
  activeSceneEntityWallMeasurementLabelScreenItems: readonly SceneEntityWallMeasurementLabelScreenItem[];
  lastRotationHandleCenterAngleDegreesBySceneEntityKey: Readonly<Record<string, number>>;
  sceneHistory: DesignSceneHistoryState;
  setActiveSceneViewMode: (sceneViewMode: SceneViewMode) => void;
  setActiveWallElevationTarget: (target: WallElevationTarget) => void;
  showPreviousWallElevationSegment: () => void;
  showNextWallElevationSegment: () => void;
  showPreviousWallElevationSide: () => void;
  showNextWallElevationSide: () => void;
  runCameraCommand: (cameraCommandTool: SceneCameraCommandTool) => void;
  clearCameraCommand: (cameraCommandId: number) => void;
  setSceneEntityWallMeasurementLabelScreenItems: (items: readonly SceneEntityWallMeasurementLabelScreenItem[]) => void;
  setActiveToolbarTool: (toolbarTool: SceneEditingTool | null) => void;
  updatePerspectiveCameraState: (cameraState: PerspectiveCameraState) => void;
  updateFloorPlanCameraState: (cameraState: OrthographicCameraState) => void;
  updateElevationCameraState: (cameraState: ElevationCameraState) => void;
  startSceneEntityPlacementCandidate: (sceneEntity: SceneEntity) => void;
  updateSceneEntityPlacementCandidate: (worldPositionInches: Point3DInches, sceneViewMode: SceneViewMode, elevationMoveFrame?: SceneEntityElevationFrame, movementFrame?: SceneEntityMovementFrame) => void;
  commitSceneEntityPlacementCandidate: () => void;
  cancelActiveSceneOperation: () => void;
  selectSceneEntity: (sceneEntity: SceneEntityRef) => void;
  toggleSceneEntitySelection: (sceneEntity: SceneEntityRef) => void;
  selectPlacedWallSegment: (wallGraphId: string, wallSegmentId: string) => void;
  clearSelection: () => void;
  startSceneEntityMoveDrag: (args: { sceneEntity: SceneEntityRef; pointerWorldInches: Point3DInches; sceneViewMode: SceneViewMode; elevationMoveFrame?: SceneEntityElevationFrame; movementFrame?: SceneEntityMovementFrame }) => void;
  updateSceneEntityMoveDrag: (pointerWorldInches: Point3DInches) => void;
  finishSceneEntityMoveDrag: () => void;
  cancelSceneEntityMoveDrag: () => void;
  startSceneEntityRotationDrag: (args: { sceneEntity: SceneEntityRef; centerPointInches: Point3DInches; pointerWorldInches: Point3DInches; startHandleCenterAngleDegrees: number }) => void;
  updateSceneEntityRotationDrag: (pointerWorldInches: Point3DInches) => void;
  finishSceneEntityRotationDrag: () => void;
  cancelSceneEntityRotationDrag: () => void;
  deleteSelectedSceneEntities: () => void;
  duplicateSelectedSceneEntities: () => void;
  updateSelectedSceneEntityWorldPositionX: (xInches: number) => void;
  updateSelectedSceneEntityWorldPositionY: (yInches: number) => void;
  updateSelectedSceneEntityDistanceFromFloor: (distanceFromFloorInches: number) => void;
  updateSelectedSceneEntityRotationZ: (zDegrees: number) => void;
  updateSelectedAssemblyDimension: (dimensionId: AssemblyDimensionId, valueInches: number) => void;
  updateSelectedAssemblyOptionValue: (optionId: string, value: AssemblyOptionValue) => void;
  updateWallSegmentDraftHover: (pointInches: Point3DInches) => void;
  startDesignReservationZonePlacementCandidate: () => void;
  updateSelectedDesignReservationZoneReservedFor: (reservedFor: DesignReservationZonePurpose) => void;
  updateSelectedDesignReservationZoneWidth: (widthInches: number) => void;
  updateSelectedDesignReservationZoneDepth: (depthInches: number) => void;
  updateSelectedDesignReservationZoneHeight: (heightInches: number) => void;
  clickWallSegmentDraftPoint: (pointInches: Point3DInches) => void;
  exitWallSegmentDraftTool: () => void;
  updateSelectedWallSegmentHeight: (heightInches: number) => void;
  updateSelectedWallSegmentThickness: (thicknessInches: number) => void;
  updateWallSegmentPreferredViewFaceSide: (args: { wallGraphId: string; wallSegmentId: string; preferredViewFaceSide: WallFaceSide }) => void;
  updateSelectedWallSegmentPreferredViewFaceSide: (preferredViewFaceSide: WallFaceSide) => void;
  updateSelectedWallSegmentCabinetPlacementFacePolicy: (faceSide: WallFaceSide, requirement: CabinetPlacementRequirement) => void;
  deleteSelectedWallSegment: () => void;
  clearActiveInteraction: () => void;
  undoDesignSceneChange: () => void;
  redoDesignSceneChange: () => void;
  restoreDesignSceneHistoryEntry: (historyEntryId: string) => void;
}>;

export type DesignSceneStoreGetter = () => DesignSceneStore;
export type DesignSceneStoreSetter = (partial: Partial<DesignSceneStore> | ((state: DesignSceneStore) => Partial<DesignSceneStore>)) => void;
